name: onnxdemo
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pytorch=1.4.0
  - torchvision=0.5.0
  - rdkit=2020.03.01
  - onnx=1.6.0
  - requests=2.23.0
  - pip
  - pip:
    - onnxruntime==1.2.0
